myproject/crm/urls.py
from django.urls import path

from myproject.crm import views as v

app_name = 'crm'


urlpatterns = [
    path('', v.person_list, name='person_list'),
    path('<int:pk>/', v.person_detail, name='person_detail'),
    path('create/', v.person_create, name='person_create'),
    path('<int:pk>/update/', v.person_update, name='person_update'),
    path('contact/send/', v.send_contact, name='send_contact'),
    path('bootstrap/create/', v.PersonBootstrapCreate.as_view(), name='person_bootstrap_create'),  # noqa E501
    path('crispy/create/', v.PersonCrispyCreate.as_view(), name='person_crispy_create'),  # noqa E501
    path('photo/create/', v.photo_create, name='photo_create'),
    path('create/ajax/', v.photo_create_ajax, name='photo_create_ajax'),
    path('vuejs/', v.person_vuejs_list, name='person_vuejs_list'),
    path('vuejs/json/', v.person_json, name='person_json'),
    path('vuejs/create/', v.person_vuejs_create, name='person_vuejs_create'),
    path('<int:pk>/vuejs/update/', v.person_vuejs_update, name='person_vuejs_update'),  # noqa E501
    path('<int:pk>/vuejs/delete/', v.person_vuejs_delete, name='person_vuejs_delete'),  # noqa E501
]

myproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('myproject.core.urls', namespace='core')),
    path('accounts/', include('myproject.accounts.urls')),  # without namespace
    path('crm/', include('myproject.crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )

myproject/crm/models.py
from django.db import models
from django.urls import reverse_lazy

from myproject.core.models import (
    Active,
    Address,
    Document,
    TimeStampedModel,
    UuidModel
)


class Person(UuidModel, TimeStampedModel, Address, Document, Active):
    first_name = models.CharField('nome', max_length=50, help_text='Digite somente o primeiro nome.')
    last_name = models.CharField('sobrenome', max_length=50, null=True, blank=True)  # noqa E501
    email = models.EmailField(null=True, blank=True)

    class Meta:
        ordering = ('first_name',)
        verbose_name = 'pessoa'
        verbose_name_plural = 'pessoas'

    @property
    def full_name(self):
        return f'{self.first_name} {self.last_name or ""}'.strip()

    def __str__(self):
        return self.full_name

    def get_absolute_url(self):
        return reverse_lazy('crm:person_detail', kwargs={'pk': self.pk})

    def to_dict(self):
        return {
            'id': self.id,
            'first_name': self.first_name,
            'last_name': self.last_name,
            'email': self.email,
        }


class Photo(models.Model):
    photo = models.ImageField('foto', upload_to='')
    person = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        verbose_name='foto',
        related_name='photos',
    )

    class Meta:
        ordering = ('pk',)
        verbose_name = 'foto'
        verbose_name_plural = 'fotos'

    def __str__(self):
        return str(self.person)

myproject/crm/forms.py
from django import forms

from .models import Person


class PersonForm0(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Person
        fields = ('first_name', 'last_name')


class PersonForm1(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Person
        fields = ('first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super(PersonForm1, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class PersonForm2(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'email')

    def __init__(self, *args, **kwargs):
        super(PersonForm2, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class PersonForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Person
        # fields = '__all__'
        fields = (
            'first_name',
            'last_name',
            'email',
            'address',
            'address_number',
            'complement',
            'district',
            'city',
            'uf',
            'cep',
            'country',
            'cpf',
            'rg',
            'cnh',
            'active',
        )

    def __init__(self, *args, **kwargs):
        super(PersonForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['active'].widget.attrs['class'] = None


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)


class PersonPhotoForm(forms.ModelForm):
    required_css_class = 'required'
    # photo = forms.ImageField(required=False)
    photo = forms.ImageField(
        required=False,
        widget=forms.ClearableFileInput(attrs={'multiple': True})
    )

    class Meta:
        model = Person
        fields = ('first_name', 'last_name', 'photo')

    def __init__(self, *args, **kwargs):
        super(PersonPhotoForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['photo'].widget.attrs['class'] = None

myproject/crm/views.py
from django.core.mail import send_mail
from django.http import JsonResponse
from django.shortcuts import redirect, render
# from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import (
    ContactForm,
    PersonForm,
    PersonForm0,
    PersonForm1,
    PersonForm2,
    PersonPhotoForm
)
from .models import Person, Photo


def person_list(request):
    template_name = 'crm/person_list.html'
    object_list = Person.objects.all()
    form = PersonForm1
    context = {'object_list': object_list, 'form': form}
    return render(request, template_name, context)


def person_detail(request, pk):
    template_name = 'crm/person_detail.html'
    obj = Person.objects.get(pk=pk)
    context = {'object': obj}
    return render(request, template_name, context)


# def person_create(request):
#     template_name = 'crm/person_form2.html'
#     form = PersonForm1(request.POST or None)

#     if request.method == 'POST':
#         if form.is_valid():
#             form.save()
#             return redirect('crm:person_list')

#     context = {'form': form}
#     return render(request, template_name, context)


def person_create(request):
    template_name = 'crm/person_form.html'
    form = PersonForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('crm:person_list')

    context = {'form': form}
    return render(request, template_name, context)


def person_update(request, pk):
    template_name = 'crm/person_form.html'
    instance = Person.objects.get(pk=pk)
    form = PersonForm(request.POST or None, instance=instance)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('crm:person_list')

    context = {'form': form}
    return render(request, template_name, context)


def send_contact(request):
    template_name = 'crm/contact_form.html'
    form = ContactForm(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            subject = form.cleaned_data.get('subject')
            message = form.cleaned_data.get('message')
            sender = form.cleaned_data.get('sender')
            send_mail(
                subject,
                message,
                sender,
                ['localhost'],
                fail_silently=False,
            )
            return redirect('core:index')

    context = {'form': form}
    return render(request, template_name, context)


class PersonBootstrapCreate(CreateView):
    model = Person
    form_class = PersonForm
    template_name = 'crm/person_bootstrap_form.html'


class PersonCrispyCreate(CreateView):
    model = Person
    form_class = PersonForm
    template_name = 'crm/person_crispy_form.html'


# def photo_create(request):
#     template_name = 'crm/person_photo_form.html'
#     form = PersonPhotoForm(request.POST or None)

#     if request.method == 'POST':
#         photo = request.FILES.get('photo')  # pega apenas um arquivo.
#         if form.is_valid():
#             person = form.save()
#             Photo.objects.create(person=person, photo=photo)
#             return redirect('crm:person_detail', person.pk)

#     context = {'form': form}
#     return render(request, template_name, context)

def photo_create(request):
    template_name = 'crm/person_photo_form.html'
    form = PersonPhotoForm(request.POST or None)

    if request.method == 'POST':
        photos = request.FILES.getlist('photo')  # pega vários arquivos.

        if form.is_valid():
            person = form.save()

            for photo in photos:
                Photo.objects.create(person=person, photo=photo)

            return redirect('crm:person_detail', person.pk)

    context = {'form': form}
    return render(request, template_name, context)


def photo_create_ajax(request):
    form = PersonForm1(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            person = form.save()
            data = [person.to_dict()]
            return JsonResponse({'data': data})


def person_vuejs_list(request):
    # Renderiza a página
    template_name = 'crm/person_vuejs_list.html'
    return render(request, template_name)


def person_json(request):
    # Retorna os dados
    persons = Person.objects.all()
    data = [person.to_dict() for person in persons]
    return JsonResponse({'data': data})


def person_vuejs_create(request):
    # Salva os dados
    form = PersonForm1(request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            person = form.save()
            data = person.to_dict()
            return JsonResponse({'data': data})


def person_vuejs_update(request, pk):
    person = Person.objects.get(pk=pk)
    form = PersonForm2(request.POST or None, instance=person)

    if request.method == 'POST':
        if form.is_valid():
            person = form.save()
            data = person.to_dict()
            return JsonResponse({'data': data})


def person_vuejs_delete(request, pk):
    if request.method == 'DELETE':
        person = Person.objects.get(pk=pk)
        person.delete()
    return JsonResponse({'status': 204})

myproject/crm/templates/crm/contact_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}
  <title>Contact</title>
{% endblock title %}

{% block content %}

  <style>
    span.required:after {
      content: "*";
      color: red;
    }
  </style>

  <h1>Send e-mail with Widget Tweaks</h1>

  <form class="form" method="POST">
    {% csrf_token %}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error {% endif %}">
        <label for="{{ field.id_for_label }}">
          {% if field.field.required %}
            <span class="required">{{ field.label }}</span>
          {% else %}
            {{ field.label }}
          {% endif %}
        </label>
        {% render_field field class="form-control" %}
        {% for error in field.errors %}
          <span class="text-muted">{{ error }}</span>
        {% endfor %}
      </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">Enviar</button>
  </form>

{% endblock content %}

{% block js %}
  <script>
    $(document).ready(function(){
      $('#id_cc_myself').removeClass('form-control');
    });
  </script>
{% endblock js %}

myproject/crm/templates/crm/person_bootstrap_form.html
<!-- person_bootstrap_form.html -->
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content %}
  <h1>Bootstrap form</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}

        {% bootstrap_form form %}

        {% buttons %}
          <button type="submit" class="btn btn-primary">Salvar</button>
        {% endbuttons %}
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_confirm_delete.html
<!-- person_delete.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Deletar</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'crm:person_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_crispy_form.html
<!-- person_crispy_form.html -->
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Crispy form</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}

        {{ form|crispy }}

        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_detail.html
<!-- person_detail.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes</h1>

  <ul>
    <li><b>Nome:</b> {{ object.full_name }}</li>
    <li><b>E-mail:</b> {{ object.email|default:'---' }}</li>
  </ul>

  <div>
    {% for item in object.photos.all %}
      {% if item.photo %}
        <img src="{{ item.photo.url }}" alt="" class="img-thumbnail" width="150px">
      {% endif %}
    {% endfor %}
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_form.html
<!-- person_form.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Formulário</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_form0.html
<!-- person_form0.html -->
{% extends "base.html" %}

{% block css %}
  <style>
    .required:after {
      content: "*";
      color: red;
    }
    .errorlist {
      list-style: none;
      color: red;
    }
  </style>
{% endblock css %}

{% block content %}
  <h1>Formulário</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST">
      {% csrf_token %}
      <div class="col-sm-6">
        <div class="form-group">
          <label for="id_first_name" class="required">Nome</label>
          <input id="id_first_name" type="text" name="first_name" class="form-control">
          {{ form.first_name.errors }}
        </div>

        <div class="form-group">
          <label for="id_last_name">Sobrenome</label>
          <input id="id_last_name" type="text" name="last_name" class="form-control">
          {{ form.last_name.errors }}
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_form1.html
<!-- person_form1.html -->
{% extends "base.html" %}

{% block css %}
  <style>
    .required:after {
      content: "*";
      color: red;
    }
    .errorlist {
      list-style: none;
      color: red;
    }
  </style>
{% endblock css %}

{% block content %}
  <h1>Formulário</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST">
      {% csrf_token %}
      <div class="col-sm-6">
        <div class="form-group">
          <!-- <label for="{{ form.first_name.id_for_label }}" class="required">Nome</label> -->
          {{ form.first_name.label_tag }}
          {{ form.first_name }}
          {{ form.first_name.errors }}
        </div>

        <div class="form-group">
          {{ form.last_name.label_tag }}
          {{ form.last_name }}
          {{ form.last_name.errors }}
        </div>

        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_form2.html
<!-- person_form2.html -->
{% extends "base.html" %}

{% block css %}
  <style>
    .required:after {
      content: "*";
      color: red;
    }
    .errorlist {
      list-style: none;
      color: red;
    }
  </style>
{% endblock css %}

{% block content %}
  <h1>Formulário</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST">
      {% csrf_token %}
      <div class="col-sm-6">
        <!-- {% for field in form %}
          <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% if field.help_text %}
              <small class="text-muted">{{ field.help_text|safe }}</small>
            {% endif %}
          </div>
        {% endfor %} -->
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_list.html
<!-- person_list.html -->
{% extends "base.html" %}

{% block content %}
  <h1>
    Lista
    <a class="btn btn-primary" href="{% url 'crm:person_create' %}">Adicionar</a>
    <a class="btn btn-primary" href="{% url 'crm:photo_create' %}">Adicionar com Foto</a>
    <a class="btn btn-primary" style="color: white;" data-toggle="modal" data-target="#myModal">Adicionar via Ajax</a>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{{ object.get_absolute_url }}">{{ object.full_name }}</a>
          </td>
          <td>{{ object.email|default:'---' }}</td>
          <td>
            <a href="{% url 'crm:person_update' object.pk %}">
              <i class="fa fa-edit"></i>
            </a>
            <a href="{ url 'crm:person_delete' object.pk %}" style="padding-left: 7px">
              <i class="fa fa-close no"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  {% include "includes/pagination.html" %}

  {% include "./person_modal.html" %}
{% endblock content %}

{% block js %}


<script>
  $('form').on('submit', function(e) {
    let url = '/crm/create/ajax/'
    let postData = $('form').serialize();
    $.ajax({
      url: url,
      type: 'POST',
      data: postData,
      success: function(response) {
        addItem(response)
      },
      error: function(xhr) {
        console.log('Erro')
      },
      complete: function() {
        closeModal()
      }
    });
    e.preventDefault();
  });

  function addItem(response) {
    const data = response.data[0];
    const template = '<tr>' +
    '<td>' + data.first_name + ' ' + data.last_name + '</td>' +
    '<td>' + data.email + '</td>' +
    '</tr>'

    $('table tbody').append(template)
  };

  function closeModal() {
    $('#myModal').modal('hide');
    // Limpa os campos
    $('#id_first_name').val('');
    $('#id_last_name').val('');
    $('#id_email').val('');
  }
</script>

{% endblock js %}

myproject/crm/templates/crm/person_modal.html
<!-- person_modal.html -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Adicionar Pessoa</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <!-- Formulario -->
      <form>
        <div class="modal-body">
          {% csrf_token %}
          <div class="form-group">
            {{ form.as_p }}
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </form>
    </div>
  </div>
</div>

myproject/crm/templates/crm/person_photo_form.html
<!-- person_photo_form.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Formulário com Foto</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

myproject/crm/templates/crm/person_vuejs_list.html
<!-- person_vuejs_list.html -->
{% extends "base.html" %}

{% block css %}

<style>
  .form-inline {
    justify-content: space-between;
    margin-bottom: 10px;
  }
  .form-control {
    margin-left: 10px;
  }
  .is-link {
    cursor: pointer;
  }
  .link {
    color:  #007bff;
  }
</style>

{% endblock css %}

{% block content %}

<div id="app">
  <div>
    <h1>Pessoas com VueJS</h1>
  </div>

  <div>
    <form @submit.prevent="submitForm" @keyup.enter="submitForm" class="form-inline" method="POST">
      <div class="form-group">
        <label class="required">Nome</label>
        <input type="text" v-model="form.first_name" class="form-control">
      </div>
      <div class="form-group">
        <label class="required">Sobrenome</label>
        <input type="text" v-model="form.last_name" class="form-control">
      </div>
      <div class="form-group">
        <label class="required">E-mail</label>
        <input type="email" v-model="form.email" class="form-control">
      </div>
      <div class="form-group">
        <button type="submit" class="btn btn-primary">Salvar</button>
      </div>
    </form>
  </div>

  <table class="table">
    <thead>
      <tr>
        <th>Nome</th>
        <th>E-mail</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      <tr v-for="person in persons" :key="person.id">
        <td>
          <a :href="'/crm/' + person.id">${ person | fullName }</a>
        </td>
        <td>${ person.email }</td>
        <td>
          <i class="fa fa-pencil-square-o link is-link" data-toggle="modal" data-target="#myModal" @click="editPerson(person)"></i>
          <i class="fa fa-close no is-link ml-2" @click="deletePerson(person)"></i>
        </td>
      </tr>
    </tbody>
  </table>

  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">Editar</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form @submit.prevent="submitEditForm" class="form-horizontal" method="POST">
          <div class="modal-body">
            <div class="form-group">
              <label class="required">Nome</label>
              <input type="text" v-model="editForm.first_name" class="form-control">
            </div>
            <div class="form-group">
              <label class="required">Sobrenome</label>
              <input type="text" v-model="editForm.last_name" class="form-control">
            </div>
            <div class="form-group">
              <label class="required">E-mail</label>
              <input type="text" v-model="editForm.email" class="form-control">
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal" ref="clickMe">Fechar</button>
            <button type="submit" class="btn btn-primary">Salvar</button>
          </div>
        </form>
      </div>
    </div>
  </div>

</div>

{% endblock content %}

{% block vuejs %}

<script>
  axios.defaults.xsrfHeaderName = "X-CSRFToken";
  axios.defaults.xsrfCookieName = "csrftoken";
  var app = new Vue({
    el: '#app',
    delimiters: ['${', '}'],
    data: {
      persons: [],
      form: {
        first_name: '',
        last_name: '',
        email: '',
      },
      editForm: {
        id: '',
        first_name: '',
        last_name: '',
        email: '',
      }
    },
    created() {
      this.getData()
    },
    filters: {
      fullName(value) {
        return value.first_name + ' ' + value.last_name
      }
    },
    methods: {
      getData() {
        axios.get('/crm/vuejs/json/')
        .then(response => {
          this.persons = response.data.data
        })
      },
      submitForm() {
        // Caso queira enviar uma string de valores...
        // const payload = JSON.stringify(this.form)

        // Vamos trabalhar com formulário
        let bodyFormData = new FormData()

        bodyFormData.append('first_name', this.form.first_name)
        bodyFormData.append('last_name', this.form.last_name)
        bodyFormData.append('email', this.form.email)

        axios.post('/crm/vuejs/create/', bodyFormData)
          .then(response => {
            this.persons.push(response.data.data)
          })
          this.form = {}
      },
      editPerson(item) {
        this.editForm.id = item.id
        this.editForm.first_name = item.first_name
        this.editForm.last_name = item.last_name
        this.editForm.email = item.email
      },
      submitEditForm() {
        let bodyFormData = new FormData()

        bodyFormData.append('first_name', this.editForm.first_name)
        bodyFormData.append('last_name', this.editForm.last_name)
        bodyFormData.append('email', this.editForm.email)

        axios.post(`/crm/${this.editForm.id}/vuejs/update/`, bodyFormData)
          .then(response => {
            this.$refs.clickMe.click()  // Fecha o modal
            this.getData()
          })
      },
      deletePerson(item) {
        axios.delete(`/crm/${item.id}/vuejs/delete/`)
          .then(() => {
            const resIndex = this.persons.find(res => res.id === item.id);
            this.persons.splice(resIndex, 1);
          })
      }
    }
  });
</script>

{% endblock vuejs %}